# Generated by Django 2.2.6 on 2019-12-18 14:11

import catalogue.util_models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            bases=(models.Model, catalogue.util_models.info),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=(models.Model, catalogue.util_models.info),
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('start_specificity', models.CharField(choices=[('d', 'day'), ('m', 'month'), ('y', 'year'), ('c', 'century')], default='d', max_length=1)),
                ('end_specificity', models.CharField(choices=[('d', 'day'), ('m', 'month'), ('y', 'year'), ('c', 'century')], default='d', max_length=1)),
            ],
            bases=(models.Model, catalogue.util_models.info),
        ),
        migrations.CreateModel(
            name='Fragment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            bases=(models.Model, catalogue.util_models.info),
        ),
        migrations.CreateModel(
            name='Illustration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=300, null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('context', models.TextField(blank=True, null=True)),
                ('upload', models.ImageField(blank=True, null=True, upload_to='illustrations/')),
            ],
            bases=(models.Model, catalogue.util_models.info),
        ),
        migrations.CreateModel(
            name='IllustrationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('iso', models.CharField(blank=True, max_length=3, null=True)),
            ],
            bases=(models.Model, catalogue.util_models.info),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('status', models.CharField(choices=[('F', 'fiction'), ('NF', 'non-fiction')], default='NF', max_length=2)),
                ('location_type', models.CharField(choices=[('CIT', 'city'), ('COU', 'country'), ('CON', 'continent'), ('REG', 'region')], default='CIT', max_length=3)),
                ('geonameid', models.CharField(default='OHxxSasDHZsB', max_length=12, unique=True)),
                ('coordinates_polygon', models.CharField(blank=True, max_length=3000, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(models.Model, catalogue.util_models.info),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('sex', models.CharField(choices=[('F', 'female'), ('M', 'male'), ('O', 'other')], max_length=1)),
                ('notes', models.TextField(blank=True, null=True)),
                ('birth_death_date', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.Date')),
                ('place_of_birth', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='born', to='catalogue.Location')),
                ('place_of_death', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='died', to='catalogue.Location')),
            ],
            bases=(models.Model, catalogue.util_models.info),
        ),
        migrations.CreateModel(
            name='PersonWorkRelationRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            bases=(models.Model, catalogue.util_models.info),
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.PositiveIntegerField(blank=True, null=True)),
                ('volume', models.PositiveIntegerField(blank=True, null=True)),
                ('identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('e_text', models.FileField(upload_to='publication/')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Location')),
            ],
            bases=(models.Model, catalogue.util_models.info),
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('location', models.ManyToManyField(blank=True, to='catalogue.Location')),
            ],
            bases=(models.Model, catalogue.util_models.info),
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('upload', models.FileField(blank=True, null=True, upload_to='texts/')),
                ('notes', models.TextField(blank=True, default='')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Genre')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Language')),
            ],
            bases=(models.Model, catalogue.util_models.info),
        ),
        migrations.CreateModel(
            name='TextTextRelationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            bases=(models.Model, catalogue.util_models.info),
        ),
        migrations.CreateModel(
            name='WorkPublicationRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Publication')),
            ],
        ),
        migrations.CreateModel(
            name='TextTextRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='primary', to='catalogue.Text')),
                ('relation_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='catalogue.TextTextRelationType')),
                ('secondary', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='secondary', to='catalogue.Text')),
            ],
            bases=(models.Model, catalogue.util_models.info),
        ),
        migrations.AddField(
            model_name='text',
            name='relations',
            field=models.ManyToManyField(default=None, through='catalogue.TextTextRelation', to='catalogue.Text'),
        ),
        migrations.CreateModel(
            name='PublisherManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Person')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Publisher')),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Publisher'),
        ),
        migrations.CreateModel(
            name='Pseudonym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pseudonyms', to='catalogue.Person')),
            ],
            bases=(models.Model, catalogue.util_models.info),
        ),
        migrations.CreateModel(
            name='PersonWorkRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_creator', models.BooleanField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Person')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.PersonWorkRelationRole')),
                ('work_illustration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.Illustration')),
                ('work_text', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.Text')),
            ],
            bases=(models.Model, catalogue.util_models.info),
        ),
        migrations.CreateModel(
            name='PersonLocationRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('R', 'residence'), ('T', 'travel'), ('W', 'work'), ('U', 'unknown')], default=None, max_length=1)),
                ('location_name', models.CharField(default='', max_length=200, null=True)),
                ('person_name', models.CharField(default='', max_length=200, null=True)),
                ('date', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='catalogue.Date')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Location')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Periodical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('language', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Location')),
            ],
            bases=(models.Model, catalogue.util_models.info),
        ),
        migrations.CreateModel(
            name='LocationLocationRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contained', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='contained', to='catalogue.Location')),
                ('container', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='container', to='catalogue.Location')),
            ],
            bases=(models.Model, catalogue.util_models.info),
        ),
        migrations.AddField(
            model_name='location',
            name='relations',
            field=models.ManyToManyField(default=None, through='catalogue.LocationLocationRelation', to='catalogue.Location'),
        ),
        migrations.CreateModel(
            name='IllustrationCategoryRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.IllustrationCategory')),
                ('illustration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Illustration')),
            ],
        ),
    ]
