# Generated by Django 2.2.6 on 2019-11-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='geonameid',
            field=models.CharField(default='yPnZkdWeZkTd', max_length=12, unique=True),
        ),
    ]
