# Generated by Django 2.2.6 on 2019-11-08 13:26

import catalogue.util
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20191107_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextTextRelationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            bases=(models.Model, catalogue.util.info),
        ),
        migrations.AddField(
            model_name='text',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='text',
            name='relations',
            field=models.ManyToManyField(default=None, through='catalogue.TextTextRelation', to='catalogue.Text'),
        ),
        migrations.AddField(
            model_name='texttextrelation',
            name='primary',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='primary', to='catalogue.Text'),
        ),
        migrations.AddField(
            model_name='texttextrelation',
            name='secondary',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='secondary', to='catalogue.Text'),
        ),
        migrations.AddField(
            model_name='texttextrelation',
            name='relation_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='catalogue.TextTextRelationType'),
        ),
    ]
