# Generated by Django 2.2.6 on 2020-01-03 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_auto_20191218_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='geonameid',
        ),
        migrations.RemoveField(
            model_name='location',
            name='relations',
        ),
        migrations.DeleteModel(
            name='LocationLocationRelation',
        ),
    ]
