# Generated by Django 2.2.6 on 2019-11-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_auto_20191115_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='geonameid',
            field=models.CharField(default='qQgDYxjWKEKH', max_length=12, unique=True),
        ),
    ]
