# Generated by Django 2.2.6 on 2020-01-31 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_auto_20200131_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='publication_id',
            field=models.IntegerField(default=356969554891, unique=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='location',
            field=models.ManyToManyField(blank=True, to='locations.UserLoc'),
        ),
        migrations.AlterField(
            model_name='text',
            name='text_id',
            field=models.IntegerField(default=241535931698, unique=True),
        ),
    ]
