# Generated by Django 2.2.6 on 2019-11-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_auto_20191115_1400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='location',
            name='geonameid',
            field=models.CharField(default='QCJjDmtgubhl', max_length=12, unique=True),
        ),
    ]
