# Generated by Django 2.2.9 on 2020-02-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_auto_20200131_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='date',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_id',
            field=models.IntegerField(default=764212998369, unique=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='text_id',
            field=models.IntegerField(default=283418324671, unique=True),
        ),
    ]
