# Generated by Django 2.2.6 on 2019-11-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_auto_20191119_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='geonameid',
            field=models.CharField(default='gHuBNyNdIVsZ', max_length=12, unique=True),
        ),
    ]
