# Generated by Django 2.2.6 on 2019-11-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_auto_20191119_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='date_spec',
            field=models.CharField(choices=[('d', 'day'), ('m', 'month'), ('y', 'year'), ('c', 'century')], default='d', max_length=1),
        ),
        migrations.AlterField(
            model_name='location',
            name='geonameid',
            field=models.CharField(default='YiPuDJoFOVCm', max_length=12, unique=True),
        ),
    ]
