# Generated by Django 2.2.6 on 2019-11-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0011_auto_20191121_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='geonameid',
            field=models.CharField(default='ZjPabOYqXtid', max_length=12, unique=True),
        ),
    ]
