# Generated by Django 2.2.6 on 2019-11-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0012_auto_20191121_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='geonameid',
            field=models.CharField(default='fofNYTRTjeGC', max_length=12, unique=True),
        ),
    ]
