# Generated by Django 2.2.6 on 2019-11-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0013_auto_20191121_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='geonameid',
            field=models.CharField(default='HXhqsqEDBemT', max_length=12, unique=True),
        ),
    ]
