# Generated by Django 2.2.9 on 2020-02-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0014_auto_20200204_1724'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Binding',
            new_name='Type',
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_id',
            field=models.IntegerField(default=745859625613, unique=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='text_id',
            field=models.IntegerField(default=584538669142, unique=True),
        ),
    ]
