# Generated by Django 2.2.6 on 2019-11-22 09:46

import catalogue.util_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0015_auto_20191121_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('iso', models.CharField(blank=True, max_length=3, null=True)),
            ],
            bases=(models.Model, catalogue.util_models.info),
        ),
        migrations.AlterField(
            model_name='location',
            name='geonameid',
            field=models.CharField(default='zqrISdiWOtnx', max_length=12, unique=True),
        ),
    ]
