# Generated by Django 2.2.9 on 2020-02-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0015_auto_20200211_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_id',
            field=models.IntegerField(default=579524867128, unique=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='text_id',
            field=models.IntegerField(default=594163877912, unique=True),
        ),
    ]
