# Generated by Django 2.2.6 on 2019-11-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0016_auto_20191122_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='geonameid',
            field=models.CharField(default='iyScvKdWZJuL', max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='language',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
