# Generated by Django 2.2.6 on 2019-11-22 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0017_auto_20191122_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='geonameid',
            field=models.CharField(default='OtfWPsgQnKhP', max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Language'),
        ),
    ]
