# Generated by Django 2.2.6 on 2019-11-27 15:49

import catalogue.util_models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0018_auto_20191122_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_spec', models.CharField(choices=[('d', 'day'), ('m', 'month'), ('y', 'year'), ('c', 'century')], default='d', max_length=1)),
                ('end_spec', models.CharField(choices=[('d', 'day'), ('m', 'month'), ('y', 'year'), ('c', 'century')], default='d', max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='person',
            name='date_of_death',
        ),
        migrations.RemoveField(
            model_name='person',
            name='date_spec',
        ),
        migrations.RemoveField(
            model_name='person',
            name='pseudonyms',
        ),
        migrations.RemoveField(
            model_name='person',
            name='residence',
        ),
        migrations.RemoveField(
            model_name='personlocationrelation',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='personlocationrelation',
            name='location_function',
        ),
        migrations.RemoveField(
            model_name='personlocationrelation',
            name='start_date',
        ),
        migrations.AddField(
            model_name='personlocationrelation',
            name='relation',
            field=models.CharField(choices=[('R', 'residence'), ('T', 'travel'), ('B', 'birth'), ('D', 'death'), ('W', 'work'), ('U', 'unknown')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='location',
            name='geonameid',
            field=models.CharField(default='WhGbEJATVBmG', max_length=12, unique=True),
        ),
        migrations.CreateModel(
            name='Pseudonym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pseudonyms', to='catalogue.Person')),
            ],
            bases=(models.Model, catalogue.util_models.info),
        ),
        migrations.AddField(
            model_name='personlocationrelation',
            name='date',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='catalogue.Date'),
        ),
    ]
