# Generated by Django 2.2.9 on 2020-02-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0019_auto_20200211_1413'),
        ('catalogue', '0018_auto_20200211_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='date',
            new_name='year',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='location',
        ),
        migrations.AddField(
            model_name='publication',
            name='location',
            field=models.ManyToManyField(blank=True, to='locations.UserLoc'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_id',
            field=models.IntegerField(default=362457994888, unique=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='text_id',
            field=models.IntegerField(default=619279632134, unique=True),
        ),
    ]
