# Generated by Django 2.2.9 on 2020-02-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0023_auto_20200212_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='publication_id',
            field=models.IntegerField(default=127723974263, unique=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='text_id',
            field=models.IntegerField(default=789845926726, unique=True),
        ),
        migrations.DeleteModel(
            name='PersonWorkRelation',
        ),
        migrations.DeleteModel(
            name='PersonWorkRelationRole',
        ),
    ]
