# Generated by Django 2.2.9 on 2020-02-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0031_auto_20200214_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='illustrationpublicationrelation',
            old_name='text',
            new_name='illustration',
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_id',
            field=models.IntegerField(default=469773286381, unique=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='text_id',
            field=models.IntegerField(default=633859825128, unique=True),
        ),
    ]
