# Generated by Django 2.2.9 on 2020-02-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0033_auto_20200219_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='start_end_date',
        ),
        migrations.AddField(
            model_name='publisher',
            name='closure',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='founded',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_id',
            field=models.IntegerField(default=948786199124, unique=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='text_id',
            field=models.IntegerField(default=111239455496, unique=True),
        ),
    ]
