# Generated by Django 2.2.9 on 2020-02-19 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0037_auto_20200219_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishermanager',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='publishermanager',
            name='publisher',
        ),
        migrations.RenameField(
            model_name='illustrationcategory',
            old_name='description',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='illustrationcategory',
            name='category',
        ),
        migrations.AddField(
            model_name='illustration',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.IllustrationCategory'),
        ),
        migrations.AddField(
            model_name='illustrationcategory',
            name='name',
            field=models.CharField(default='a', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_id',
            field=models.IntegerField(default=312471344778, unique=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='text_id',
            field=models.IntegerField(default=694824336293, unique=True),
        ),
        migrations.DeleteModel(
            name='IllustrationCategoryRelation',
        ),
        migrations.DeleteModel(
            name='PublisherManager',
        ),
    ]
