# Generated by Django 2.2.10 on 2020-03-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0046_auto_20200304_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='illustration',
            name='upload',
            field=models.ImageField(blank=True, default='', null=True, upload_to='illustrations/'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_id',
            field=models.IntegerField(default=838836474172, unique=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='text_id',
            field=models.IntegerField(default=894283818837842426),
        ),
    ]
