# Generated by Django 2.2.10 on 2020-03-25 16:01

from django.db import migrations, models
import django.db.models.deletion
import utils.model_util


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0054_auto_20200319_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodical',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='periodical',
            name='language',
        ),
        migrations.RemoveField(
            model_name='periodical',
            name='location',
        ),
        migrations.RemoveField(
            model_name='periodical',
            name='start_date',
        ),
        migrations.AddField(
            model_name='periodical',
            name='closure',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='periodical',
            name='founded',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_id',
            field=models.IntegerField(default=279261346638),
        ),
        migrations.AlterField(
            model_name='text',
            name='text_id',
            field=models.IntegerField(default=868388718122969877),
        ),
        migrations.CreateModel(
            name='PeriodicalPublicationRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.PositiveIntegerField(blank=True, null=True)),
                ('issue', models.PositiveIntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=300)),
                ('periodical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Periodical')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Publication')),
            ],
            bases=(models.Model, utils.model_util.info),
        ),
    ]
