# Generated by Django 2.2.10 on 2020-03-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0055_auto_20200325_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodicalpublicationrelation',
            name='title',
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_id',
            field=models.IntegerField(default=182972394748),
        ),
        migrations.AlterField(
            model_name='text',
            name='text_id',
            field=models.IntegerField(default=263756949132483793),
        ),
    ]
