# Generated by Django 2.2.10 on 2020-04-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0069_auto_20200421_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publication',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_id',
            field=models.IntegerField(default=753956138766),
        ),
        migrations.AlterField(
            model_name='text',
            name='text_id',
            field=models.IntegerField(default=836756614243889551),
        ),
    ]
