# Generated by Django 2.2.10 on 2020-04-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0074_auto_20200421_1050'),
        ('catalogue', '0070_auto_20200421_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodical',
            name='location',
            field=models.ManyToManyField(blank=True, to='locations.UserLoc'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_id',
            field=models.IntegerField(default=577843646774),
        ),
        migrations.AlterField(
            model_name='text',
            name='text_id',
            field=models.IntegerField(default=186543676582845594),
        ),
    ]
