# Generated by Django 2.2.10 on 2020-04-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0077_auto_20200421_1107'),
        ('catalogue', '0071_auto_20200421_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='location',
            field=models.ManyToManyField(blank=True, to='locations.UserLoc'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_id',
            field=models.IntegerField(default=386787426951),
        ),
        migrations.AlterField(
            model_name='text',
            name='text_id',
            field=models.IntegerField(default=719732576676566286),
        ),
    ]
