# Generated by Django 2.2.10 on 2020-04-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0072_auto_20200421_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='illustration',
            name='page_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='illustrationpublicationrelation',
            name='page',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_id',
            field=models.IntegerField(default=967691994338),
        ),
        migrations.AlterField(
            model_name='text',
            name='text_id',
            field=models.IntegerField(default=512643278143239698),
        ),
        migrations.AlterField(
            model_name='textpublicationrelation',
            name='end_page',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='textpublicationrelation',
            name='start_page',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
