# Generated by Django 2.2.10 on 2020-04-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0073_auto_20200421_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='publication_id',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='text',
            name='text_id',
            field=models.CharField(default='', max_length=30),
        ),
    ]
