# Generated by Django 2.2.10 on 2020-04-29 11:24

from django.db import migrations, models
import partial_date.partial_date
import utils.model_util


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0074_auto_20200421_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=9)),
                ('pd', partial_date.partial_date.PartialDateField()),
            ],
            bases=(models.Model, utils.model_util.info),
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'ordering': ['name']},
        ),
    ]
