# Generated by Django 2.2.10 on 2020-05-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0075_auto_20200429_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='illustration',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='illustration',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='periodical',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='periodical',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publisher',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publisher',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='text',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='text',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='illustration',
            name='page_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
