# Generated by Django 2.2.6 on 2020-01-23 13:43

from django.db import migrations, models
import django.db.models.deletion
import utils.model_util


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('utilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('sex', models.CharField(choices=[('F', 'female'), ('M', 'male'), ('O', 'other')], max_length=1)),
                ('notes', models.TextField(blank=True, null=True)),
                ('birth_death_date', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilities.Date')),
                ('place_of_birth', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='born', to='locations.UserLoc')),
                ('place_of_death', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='died', to='locations.UserLoc')),
            ],
            bases=(models.Model, utils.model_util.info),
        ),
        migrations.CreateModel(
            name='Pseudonym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pseudonyms', to='persons.Person')),
            ],
            bases=(models.Model, utils.model_util.info),
        ),
        migrations.CreateModel(
            name='PersonLocationRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('R', 'residence'), ('T', 'travel'), ('W', 'work'), ('U', 'unknown')], default=None, max_length=1)),
                ('location_name', models.CharField(default='', max_length=200, null=True)),
                ('person_name', models.CharField(default='', max_length=200, null=True)),
                ('date', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='utilities.Date')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.UserLoc')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Person')),
            ],
            bases=(models.Model, utils.model_util.info),
        ),
    ]
