# Generated by Django 2.2.9 on 2020-02-04 15:44

from django.db import migrations, models
import utils.model_util


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            bases=(models.Model, utils.model_util.info),
        ),
    ]
