# Generated by Django 2.2.9 on 2020-02-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0007_auto_20200204_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='function',
        ),
        migrations.AddField(
            model_name='person',
            name='function',
            field=models.ManyToManyField(blank=True, to='persons.Function'),
        ),
        migrations.RemoveField(
            model_name='person',
            name='pseudonym',
        ),
        migrations.AddField(
            model_name='person',
            name='pseudonym',
            field=models.ManyToManyField(blank=True, to='persons.Pseudonym'),
        ),
    ]
