# Generated by Django 2.2.9 on 2020-02-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0013_auto_20200211_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='place_of_birth',
            new_name='birth_place',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='place_of_death',
            new_name='death_place',
        ),
        migrations.RemoveField(
            model_name='person',
            name='birth_death_date',
        ),
        migrations.RemoveField(
            model_name='personlocationrelation',
            name='date',
        ),
        migrations.AddField(
            model_name='person',
            name='birth_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='death_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personlocationrelation',
            name='end_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personlocationrelation',
            name='start_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='function',
            field=models.ManyToManyField(blank=True, to='persons.Function'),
        ),
    ]
