# Generated by Django 2.2.9 on 2020-02-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0016_auto_20200212_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='function',
            field=models.ManyToManyField(blank=True, to='persons.Function'),
        ),
        migrations.AlterField(
            model_name='personlocationrelation',
            name='relation',
            field=models.CharField(choices=[('R', 'residence'), ('T', 'travel'), ('W', 'work'), ('U', 'unknown')], max_length=1, null=None),
        ),
    ]
