# Generated by Django 2.2.9 on 2020-02-14 13:34

from django.db import migrations, models
import django.db.models.deletion
import utils.model_util


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0024_auto_20200214_1434'),
        ('persons', '0017_auto_20200212_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonWorkRelationRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            bases=(models.Model, utils.model_util.info),
        ),
        migrations.AlterField(
            model_name='person',
            name='function',
            field=models.ManyToManyField(blank=True, to='persons.Function'),
        ),
        migrations.CreateModel(
            name='PersonTextRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Person')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.PersonWorkRelationRole')),
                ('text', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.Text')),
            ],
            bases=(models.Model, utils.model_util.info),
        ),
        migrations.CreateModel(
            name='PersonIllustrationRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Person')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.PersonWorkRelationRole')),
                ('work_illustration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.Illustration')),
            ],
            bases=(models.Model, utils.model_util.info),
        ),
    ]
