# Generated by Django 2.2.9 on 2020-02-14 13:38

from django.db import migrations, models
import django.db.models.deletion
import utils.model_util


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0018_auto_20200214_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonTextRelationRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            bases=(models.Model, utils.model_util.info),
        ),
        migrations.RenameModel(
            old_name='PersonWorkRelationRole',
            new_name='PersonIllustrationRelationRole',
        ),
        migrations.AlterField(
            model_name='person',
            name='function',
            field=models.ManyToManyField(blank=True, to='persons.Function'),
        ),
        migrations.AlterField(
            model_name='persontextrelation',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.PersonTextRelationRole'),
        ),
    ]
