# Generated by Django 2.2.9 on 2020-02-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0019_auto_20200214_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personillustrationrelationrole',
            old_name='role',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='persontextrelationrole',
            old_name='role',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='person',
            name='function',
            field=models.ManyToManyField(blank=True, to='persons.Function'),
        ),
    ]
