# Generated by Django 2.2.9 on 2020-02-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0029_auto_20200214_1514'),
        ('persons', '0022_auto_20200214_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personillustrationrelation',
            old_name='work_illustration',
            new_name='illustration',
        ),
        migrations.AlterField(
            model_name='person',
            name='function',
            field=models.ManyToManyField(blank=True, to='persons.Function'),
        ),
        migrations.AlterUniqueTogether(
            name='personillustrationrelation',
            unique_together={('role', 'person', 'illustration')},
        ),
        migrations.AlterUniqueTogether(
            name='persontextrelation',
            unique_together={('role', 'person', 'text')},
        ),
    ]
