# Generated by Django 2.2.9 on 2020-02-19 11:21

from django.db import migrations, models
import utils.model_util


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0025_auto_20200214_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            bases=(models.Model, utils.model_util.info),
        ),
        migrations.RenameField(
            model_name='personillustrationrelationrole',
            old_name='description',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='persontextrelationrole',
            old_name='description',
            new_name='notes',
        ),
        migrations.AlterField(
            model_name='person',
            name='function',
            field=models.ManyToManyField(blank=True, to='persons.Function'),
        ),
    ]
