# Generated by Django 2.2.9 on 2020-02-27 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0034_auto_20200220_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='function',
        ),
        migrations.DeleteModel(
            name='function',
        ),
    ]
