# Generated by Django 2.2.10 on 2020-03-19 16:22

from django.db import migrations, models
import django.db.models.deletion
import utils.model_util


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0055_auto_20200319_1722'),
        ('persons', '0038_auto_20200227_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiteraryMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('founded', models.PositiveIntegerField(blank=True, null=True)),
                ('closure', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('location', models.ManyToManyField(blank=True, to='locations.UserLoc')),
            ],
            bases=(models.Model, utils.model_util.info),
        ),
        migrations.CreateModel(
            name='PersonLiteraryMovementRelationRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            bases=(models.Model, utils.model_util.info),
        ),
        migrations.CreateModel(
            name='PersonLiteraryMovementRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('literary_movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.LiteraryMovement')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Person')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.PersonLiteraryMovementRelationRole')),
            ],
            bases=(models.Model, utils.model_util.info),
        ),
    ]
