# Generated by Django 2.2.10 on 2020-03-19 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0056_auto_20200319_1800'),
        ('persons', '0039_literarymovement_personliterarymovementrelation_personliterarymovementrelationrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='literarymovement',
            name='location',
        ),
        migrations.AddField(
            model_name='literarymovement',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.UserLoc'),
        ),
    ]
