# Generated by Django 2.2.10 on 2020-03-26 12:55

from django.db import migrations, models
import django.db.models.deletion
import utils.model_util


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0061_auto_20200326_1355'),
        ('persons', '0040_auto_20200319_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('founded', models.PositiveIntegerField(blank=True, null=True)),
                ('closure', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.UserLoc')),
            ],
            bases=(models.Model, utils.model_util.info),
        ),
        migrations.CreateModel(
            name='MovementType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            bases=(models.Model, utils.model_util.info),
        ),
        migrations.CreateModel(
            name='PersonMovementRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persons.Movement')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Person')),
            ],
            bases=(models.Model, utils.model_util.info),
        ),
        migrations.RemoveField(
            model_name='personliterarymovementrelation',
            name='literary_movement',
        ),
        migrations.RemoveField(
            model_name='personliterarymovementrelation',
            name='person',
        ),
        migrations.RemoveField(
            model_name='personliterarymovementrelation',
            name='role',
        ),
        migrations.RenameModel(
            old_name='PersonLiteraryMovementRelationRole',
            new_name='PersonMovementRelationRole',
        ),
        migrations.DeleteModel(
            name='LiteraryMovement',
        ),
        migrations.DeleteModel(
            name='PersonLiteraryMovementRelation',
        ),
        migrations.AddField(
            model_name='personmovementrelation',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.PersonMovementRelationRole'),
        ),
        migrations.AddField(
            model_name='movement',
            name='movement_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='persons.MovementType'),
        ),
    ]
