# Generated by Django 2.2.10 on 2020-03-26 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0042_auto_20200326_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personmovementrelation',
            name='movement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='persons.Movement'),
            preserve_default=False,
        ),
    ]
