# Generated by Django 2.2.10 on 2020-03-26 14:45

from django.db import migrations, models
import django.db.models.deletion
import utils.model_util


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0043_auto_20200326_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonPersonRelationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            bases=(models.Model, utils.model_util.info),
        ),
        migrations.CreateModel(
            name='PersonPersonRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person1', to='persons.Person')),
                ('person2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person2', to='persons.Person')),
                ('relation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.PersonPersonRelationType')),
            ],
            bases=(models.Model, utils.model_util.info),
        ),
    ]
