# Generated by Django 2.2.10 on 2020-03-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0044_personpersonrelation_personpersonrelationtype'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='personpersonrelation',
            constraint=models.UniqueConstraint(fields=('person1', 'person2', 'relation_type'), name='unique_personpersonrelation'),
        ),
    ]
