# Generated by Django 2.2.10 on 2020-04-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0046_personperiodicalrelation_personperiodicalrelationrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='persontextrelation',
            name='published_under',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
