from django.urls import include,path,re_path

from . import views


app_name = 'locations'
urlpatterns = [
	path('map/',views.map, name='map'),
	path('map_ll/',views.map_ll, name='map_ll'),
	path('map_ll_alpha/',views.map_ll_alpha, name='map_ll_alpha'),
	path('map_search/',views.map_search, name='map_search'),
	path('map_search_rf/',views.map_search_rf, name='map_search_rf'),
	path('map_draw/',views.map_draw, name='map_draw'),
	path('ajax_get_connections/<str:app_name>/<str:model_name>/<int:pk>',
		views.ajax_get_connections, name='ajax_get_connections'),
	path('ajax_instance/<str:app_name>/<str:model_name>/<int:pk>',
		views.ajax_instance, name='ajax_instance'),
	path('ajax_instances/<str:app_name>/<str:model_name>/<str:pks>',
		views.ajax_instances, name='ajax_instances'),
	path('ajax_popup/<str:markerid>/',views.ajax_popup, name='ajax_popup'),
	path('ajax_popup/<str:markerid>/<str:lat>/<str:lng>/',views.ajax_popup, 
		name='ajax_popup'),
	path('ajax_popup/<str:markerid>/<str:main_instance_markerid>/',
		views.ajax_popup,name='ajax_popup'),
	path('ajax_links/<str:markerid>/',views.ajax_links,name='ajax_links'),
	path('ajax_links/<str:markerid>/',views.ajax_links,name='ajax_links'),
	path('geojson_file/<str:filename>/',views.geojson_file, name='geojson_file'),
	path('geojson_file/geojson/<str:filename>/',views.geojson_file, 
		name='geojson_file'),
	path('show_links/<str:app_name>/<str:model_name>/<int:pk>/',
		views.show_links,name='show_links'),
	path('map/<str:location_name>/',views.mapp, name='mapp'),
	path('delete/<int:pk>/<str:model_name>', views.delete, name='delete'),
	path('add_location/', views.edit_location, name='add_location'),
	path('add_location/<str:view>', views.edit_location, name='add_location'),
	path('edit_location/<int:pk>', views.edit_location, name='edit_location'),
	path('edit_location/<int:pk>/<str:focus>', views.edit_location, 
		name='edit_location'),
	path('style/', views.style_list, name='style_list'),
	path('add_style/', views.edit_style, name='add_style'),
	path('add_style/<str:view>', views.edit_style, name='add_style'),
	path('edit_style/<int:pk>', views.edit_style, name='edit_style'),
	path('edit_style/<int:pk>/<str:focus>', views.edit_style, name='edit_style'),
	path('figure/', views.figure_list, name='figure_list'),
	path('add_figure/', views.edit_figure, name='add_figure'),
	path('add_figure/<str:view>', views.edit_figure, name='add_figure'),
	path('edit_figure/<int:pk>', views.edit_figure, name='edit_figure'),
	path('edit_figure/<int:pk>/<str:focus>', views.edit_figure, name='edit_figure'),
	path('add_location_status/',views.add_location_status, 
		name='add_location_status'),
	path('add_location_status/<int:pk>',views.add_location_status, 
		name='add_location_status'),
	path('add_location_precision/',views.add_location_precision, 
		name='add_location_precision'),
	path('add_location_precision/<int:pk>',views.add_location_precision, 
		name='add_location_precision'),
	path('add_location_type/',views.add_location_type, name='add_location_type'),
	path('add_location_type/<int:pk>',views.add_location_type, 
		name='add_location_type'),
]
