# Generated by Django 2.2.6 on 2020-01-23 13:43

from django.db import migrations, models
import utils.model_util


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('start_specificity', models.CharField(choices=[('d', 'day'), ('m', 'month'), ('y', 'year'), ('c', 'century')], default='d', max_length=1)),
                ('end_specificity', models.CharField(choices=[('d', 'day'), ('m', 'month'), ('y', 'year'), ('c', 'century')], default='d', max_length=1)),
            ],
            bases=(models.Model, utils.model_util.info),
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('iso', models.CharField(blank=True, max_length=3, null=True)),
            ],
            bases=(models.Model, utils.model_util.info),
        ),
    ]
