# Generated by Django 2.2.9 on 2020-02-20 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Date',
        ),
    ]
