# Generated by Django 2.2.10 on 2020-04-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0002_delete_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='generic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
