from django.urls import include,path,re_path

from . import views


app_name = 'catalogue'
urlpatterns = [
	path('',views.TextView.as_view(),name='text_view'),
	path('add_illustration/', views.edit_illustration, name='add_illustration'),
	path('add_illustration_category/', views.add_illustration_category, 
		name='add_illustration_category'),
	path('add_text/', views.edit_text, name='add_text'),
	path('add_periodical/', views.edit_periodical, name='add_periodical'),
	path('add_publication/', views.edit_publication, name='add_publication'),
	path('add_publisher/', views.edit_publisher, name='add_publisher'),
	path('add_publication_type/', views.add_type, name='add_publication_type'),
	path('add_illustration/<str:view>', views.edit_illustration, 
		name='add_illustration'),
	path('add_text/<str:view>', views.edit_text, name='add_text'),
	path('add_periodical/<str:view>', views.edit_periodical, name='add_periodical'),
	path('add_publication/<str:view>', views.edit_publication, 
		name='add_publication'),
	path('add_publisher/<str:view>', views.edit_publisher, name='add_publisher'),
	path('add_texttext_relation_type',views.add_texttext_relation_type,
		name='add_texttext_relation_type'),
	path('edit_text/<int:pk>', views.edit_text, name='edit_text'),
	path('edit_text/<int:pk>/<str:focus>', views.edit_text, name='edit_text'),
	path('edit_periodical/<int:pk>', views.edit_periodical, name='edit_periodical'),
	path('edit_periodical/<int:pk>/<str:focus>', views.edit_periodical, name='edit_periodical'),
	path('edit_publication/<int:pk>', views.edit_publication, name='edit_publication'),
	path('edit_publication/<int:pk>/<str:focus>', views.edit_publication, 
		name='edit_publication'),
	path('edit_publisher/<int:pk>', views.edit_publisher, name='edit_publisher'),
	path('edit_publisher/<int:pk>/<str:focus>', views.edit_publisher, name='edit_publisher'),
	path('edit_illustration/<int:pk>', views.edit_illustration, 
		name='edit_illustration'),
	path('edit_illustration/<int:pk>/<str:focus>', 
		views.edit_illustration, name='edit_illustration'),
	path('text/',views.TextView.as_view(),name='text_list'),
	path('publication/',views.PublicationView.as_view(),name='publication_list'),
	path('publisher/',views.PublisherView.as_view(),name='publisher_list'),
	path('periodical/',views.PeriodicalView.as_view(),name='periodical_list'),
	path('illustration/',views.IllustrationView.as_view(),
		name='illustration_list'),
]
