# Generated by Django 2.2.6 on 2020-01-03 10:51

from django.db import migrations, models
import django.db.models.deletion
import utils.model_util


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoLoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location_type', models.CharField(choices=[('CIT', 'city'), ('COU', 'country'), ('CON', 'continent'), ('REG', 'region')], default='CIT', max_length=3)),
                ('geonameid', models.CharField(default='SPRETfanrIyp', max_length=12, unique=True)),
                ('coordinates_polygon', models.CharField(blank=True, max_length=3000, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(models.Model, utils.model_util.info),
        ),
        migrations.CreateModel(
            name='LocType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='UserLoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('loc_precision', models.CharField(choices=[('E', 'exact'), ('A', 'approximate'), ('R', 'rough')], default='A', max_length=1)),
                ('status', models.CharField(choices=[('F', 'fiction'), ('NF', 'non-fiction')], default='NF', max_length=2)),
                ('notes', models.TextField(blank=True, default='')),
                ('loc_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.LocType')),
            ],
            bases=(models.Model, utils.model_util.info),
        ),
        migrations.CreateModel(
            name='LocRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contained', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='contained', to='locations.GeoLoc')),
                ('container', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='container', to='locations.GeoLoc')),
            ],
            bases=(models.Model, utils.model_util.info),
        ),
        migrations.AddField(
            model_name='geoloc',
            name='relations',
            field=models.ManyToManyField(default=None, through='locations.LocRelation', to='locations.GeoLoc'),
        ),
        migrations.AddField(
            model_name='geoloc',
            name='user_loc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.UserLoc'),
        ),
    ]
