# Generated by Django 2.2.6 on 2020-01-31 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoloc',
            name='geonameid',
            field=models.CharField(default='LgKCVSraKUyX', max_length=12, unique=True),
        ),
    ]
