# Generated by Django 2.2.6 on 2020-01-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LocRelation',
            new_name='GeoLocsRelation',
        ),
        migrations.AlterField(
            model_name='geoloc',
            name='geonameid',
            field=models.CharField(default='OZaoqFkjOmGx', max_length=12, unique=True),
        ),
    ]
