# Generated by Django 2.2.6 on 2020-01-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20200103_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoloc',
            name='geonameid',
            field=models.CharField(default='vcEGIqyoRtXZ', max_length=12, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='geolocsrelation',
            unique_together={('container', 'contained')},
        ),
    ]
