# Generated by Django 2.2.6 on 2020-01-31 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_auto_20200131_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoloc',
            name='geonameid',
            field=models.CharField(default='QmZnbKqHmQML', max_length=12, unique=True),
        ),
    ]
