# Generated by Django 2.2.6 on 2020-01-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_auto_20200108_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoloc',
            name='geonameid',
            field=models.CharField(default='fQocNEhwKDgf', max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='geoloc',
            name='location_type',
            field=models.CharField(choices=[('CITY', 'city'), ('COUNTRY', 'country'), ('CONTINENT', 'continent'), ('REGION', 'region')], default='CITY', max_length=3),
        ),
    ]
