# Generated by Django 2.2.9 on 2020-02-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_auto_20200131_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoloc',
            name='geonameid',
            field=models.CharField(default='ndibtuDivMUk', max_length=12, unique=True),
        ),
    ]
