# Generated by Django 2.2.6 on 2020-01-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_auto_20200110_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoloc',
            name='geonameid',
            field=models.CharField(default='nLfWdUhuRoiu', max_length=12, unique=True),
        ),
    ]
