# Generated by Django 2.2.9 on 2020-02-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_auto_20200204_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoloc',
            name='geonameid',
            field=models.CharField(default='QTdesePMPraC', max_length=12, unique=True),
        ),
    ]
