# Generated by Django 2.2.9 on 2020-02-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0012_auto_20200204_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoloc',
            name='geonameid',
            field=models.CharField(default='lPKvoUDRvGsf', max_length=12, unique=True),
        ),
    ]
