# Generated by Django 2.2.9 on 2020-02-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0014_auto_20200204_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoloc',
            name='geonameid',
            field=models.CharField(default='ZATcsNdrdfrn', max_length=12, unique=True),
        ),
    ]
