# Generated by Django 2.2.9 on 2020-02-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0015_auto_20200211_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoloc',
            name='geonameid',
            field=models.CharField(default='ONsrDUvYcXHl', max_length=12, unique=True),
        ),
    ]
