# Generated by Django 2.2.9 on 2020-02-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0018_auto_20200211_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoloc',
            name='geonameid',
            field=models.CharField(default='oasRKkcFvnia', max_length=12, unique=True),
        ),
    ]
