# Generated by Django 2.2.9 on 2020-02-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0019_auto_20200211_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoloc',
            name='geonameid',
            field=models.CharField(default='yBrInjLrYBAR', max_length=12, unique=True),
        ),
    ]
