# Generated by Django 2.2.9 on 2020-02-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0021_auto_20200211_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoloc',
            name='geonameid',
            field=models.CharField(default='iykMBVRksClX', max_length=12, unique=True),
        ),
    ]
