# Generated by Django 2.2.9 on 2020-02-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0022_auto_20200212_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoloc',
            name='geonameid',
            field=models.CharField(default='vtRPrdmlUFmZ', max_length=12, unique=True),
        ),
    ]
