# Generated by Django 2.2.9 on 2020-02-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0023_auto_20200212_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoloc',
            name='geonameid',
            field=models.CharField(default='dQEuPXOxQhny', max_length=12, unique=True),
        ),
    ]
