# Generated by Django 2.2.9 on 2020-02-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0026_auto_20200214_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoloc',
            name='geonameid',
            field=models.CharField(default='ejbqXqogZgdx', max_length=12, unique=True),
        ),
    ]
