# Generated by Django 2.2.9 on 2020-02-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0031_auto_20200214_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoloc',
            name='geonameid',
            field=models.CharField(default='mvgizdtpgRup', max_length=12, unique=True),
        ),
    ]
