# Generated by Django 2.2.9 on 2020-02-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0032_auto_20200219_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoloc',
            name='geonameid',
            field=models.CharField(default='QkpEpVNfmHAM', max_length=12, unique=True),
        ),
    ]
