# Generated by Django 2.2.9 on 2020-02-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0038_auto_20200219_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoloc',
            name='geonameid',
            field=models.CharField(default='wcQvJmCWRXVi', max_length=12, unique=True),
        ),
    ]
