# Generated by Django 2.2.9 on 2020-02-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0040_auto_20200220_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoloc',
            name='geonameid',
            field=models.CharField(default='cnyHRngCjtna', max_length=12, unique=True),
        ),
    ]
