# Generated by Django 2.2.9 on 2020-02-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0043_auto_20200227_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoloc',
            name='geonameid',
            field=models.CharField(default='PRNPLqxadZiU', max_length=12, unique=True),
        ),
    ]
