# Generated by Django 2.2.10 on 2020-03-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0046_auto_20200304_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoloc',
            name='geonameid',
            field=models.CharField(default='oVnKLuLJsXKu', max_length=12, unique=True),
        ),
    ]
