# Generated by Django 2.2.10 on 2020-03-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0048_auto_20200312_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoloc',
            name='geonameid',
            field=models.CharField(default='lVtBSOPmOqJY', max_length=12, unique=True),
        ),
    ]
