# Generated by Django 2.2.10 on 2020-03-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0049_auto_20200318_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoloc',
            name='geonameid',
            field=models.CharField(default='FRgsHNIWQmTA', max_length=12, unique=True),
        ),
    ]
