# Generated by Django 2.2.10 on 2020-03-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0053_auto_20200318_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoloc',
            name='geonameid',
            field=models.CharField(default='svdbHwJFVlAj', max_length=12, unique=True),
        ),
    ]
