# Generated by Django 2.2.10 on 2020-03-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0054_auto_20200318_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoloc',
            name='geonameid',
            field=models.CharField(default='euJyNvGJMegS', max_length=12, unique=True),
        ),
    ]
