# Generated by Django 2.2.10 on 2020-03-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0056_auto_20200319_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoloc',
            name='geonameid',
            field=models.CharField(default='gdexqzkHOHSn', max_length=12, unique=True),
        ),
    ]
