# Generated by Django 2.2.10 on 2020-03-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0057_auto_20200319_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoloc',
            name='geonameid',
            field=models.CharField(default='hLLZNJaXCkSx', max_length=12, unique=True),
        ),
    ]
