# Generated by Django 2.2.10 on 2020-03-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0058_auto_20200325_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoloc',
            name='geonameid',
            field=models.CharField(default='eppDiqbpPcEZ', max_length=12, unique=True),
        ),
    ]
