# Generated by Django 2.2.10 on 2020-03-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0059_auto_20200325_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoloc',
            name='geonameid',
            field=models.CharField(default='RYIsyLnbZsuX', max_length=12, unique=True),
        ),
    ]
