# Generated by Django 2.2.10 on 2020-03-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0061_auto_20200326_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoloc',
            name='geonameid',
            field=models.CharField(default='AwygSTCxcdtv', max_length=12, unique=True),
        ),
    ]
