# Generated by Django 2.2.10 on 2020-03-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0063_auto_20200326_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoloc',
            name='geonameid',
            field=models.CharField(default='YDIhfcAGBSlZ', max_length=12, unique=True),
        ),
    ]
