# Generated by Django 2.2.10 on 2020-03-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0064_auto_20200326_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoloc',
            name='geonameid',
            field=models.CharField(default='RNaKolAOcCTx', max_length=12, unique=True),
        ),
    ]
