# Generated by Django 2.2.10 on 2020-04-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0065_auto_20200326_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloc',
            name='info',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='geoloc',
            name='geonameid',
            field=models.CharField(default='iiMlMuAZQGMx', max_length=12, unique=True),
        ),
    ]
