# Generated by Django 2.2.10 on 2020-04-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0067_auto_20200402_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoloc',
            name='geonameid',
            field=models.CharField(default='DcVxafQvCrqP', max_length=12, unique=True),
        ),
    ]
