# Generated by Django 2.2.10 on 2020-04-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0068_auto_20200406_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoloc',
            name='geonameid',
            field=models.CharField(default='roVnVCVXHzBG', max_length=12, unique=True),
        ),
    ]
