# Generated by Django 2.2.10 on 2020-04-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0069_auto_20200408_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoloc',
            name='geonameid',
            field=models.CharField(default='azIEqeWbJbnC', max_length=12, unique=True),
        ),
    ]
