# Generated by Django 2.2.10 on 2020-04-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0071_auto_20200418_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoloc',
            name='geonameid',
            field=models.CharField(default='iKdEIgfFcjsK', max_length=12, unique=True),
        ),
    ]
