# Generated by Django 2.2.10 on 2020-04-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0072_auto_20200421_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoloc',
            name='geonameid',
            field=models.CharField(default='FKvGdeGkVbPb', max_length=12, unique=True),
        ),
    ]
