# Generated by Django 2.2.10 on 2020-04-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0075_auto_20200421_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoloc',
            name='geonameid',
            field=models.CharField(default='mzifqjOINWfA', max_length=12, unique=True),
        ),
    ]
