# Generated by Django 2.2.10 on 2020-04-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0076_auto_20200421_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoloc',
            name='geonameid',
            field=models.CharField(default='xdONphDngdQH', max_length=12, unique=True),
        ),
    ]
