# Generated by Django 2.2.10 on 2020-04-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0078_auto_20200421_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoloc',
            name='geonameid',
            field=models.CharField(default='', max_length=12, unique=True),
        ),
    ]
